
coverage:
  range: 20..85 # coverage lower than 50 is red, higher than 90 green, between color code

  status:
    project: # settings affecting project coverage
      enabled: yes
      target: auto # auto % coverage target
      threshold: 25%  # allow for 25% reduction of coverage without failing

    # do not run coverage on patch nor changes
    patch: no
    changes: no
